Repository Akanksha810/CS-Bot, pull requests merged in 2020-03, with the labels that each got.

#5 Update README.md
  README.md
Labels: documentation

#6 Routing frontend
  .idea/CS-Bot.iml
  .idea/misc.xml
  assignment-2.pdf
  chatbot-ui/.babelrc
  chatbot-ui/package-lock.json
  chatbot-ui/package.json
  chatbot-ui/public/1_paQ7E6f2VyTKXHpR-aViFg.png
  chatbot-ui/public/bg-pic.jfif
  chatbot-ui/public/bot-3.jpg
  chatbot-ui/public/bot-4.png
  chatbot-ui/public/bot-5.jpg
  chatbot-ui/public/bot-6.png
  chatbot-ui/public/bot-7.png
  chatbot-ui/public/boy-avator.jpg
  chatbot-ui/public/coral-bot-icon.png
  chatbot-ui/public/girl-avator.png
  chatbot-ui/public/index.html
  chatbot-ui/public/letters_words_text_122223_1920x1080.jpg
  chatbot-ui/src/App.js
  chatbot-ui/src/components/Footer.js
  chatbot-ui/src/components/bots/ControlCoral.js
  chatbot-ui/src/components/bots/ControlIris.js
  chatbot-ui/src/containers/HomeContainer.js
  chatbot-ui/src/index.css
  chatbot-ui/src/index.js
  chatbot-ui/src/styles/components/footer.css
  chatbot-ui/src/styles/containers/home-container.css
  chatbot-ui/src/styles/fonts/PIMPBOT5.ttf
  chatbot-ui/src/styles/fonts/autodestructbb_bold.ttf
  chatbot-ui/src/styles/fonts/autodestructbb_reg.ttf
  chatbot-ui/src/styles/fonts/fontinfo.txt
  chatbot-ui/src/styles/fonts/futura/Futura Bold Italic font.ttf
  chatbot-ui/src/styles/fonts/futura/Futura Bold font.ttf
  chatbot-ui/src/styles/fonts/futura/Futura Book Italic font.ttf
  chatbot-ui/src/styles/fonts/futura/Futura Book font.ttf
  chatbot-ui/src/styles/fonts/futura/Futura Extra Black font.ttf
  chatbot-ui/src/styles/fonts/futura/Futura Heavy Italic font.ttf
  chatbot-ui/src/styles/fonts/futura/Futura Heavy font.ttf
  chatbot-ui/src/styles/fonts/futura/Futura Light Italic font.ttf
  chatbot-ui/src/styles/fonts/futura/Futura Light font.ttf
  chatbot-ui/src/styles/fonts/futura/Futura Medium Italic font.ttf
  chatbot-ui/src/styles/fonts/futura/Futura XBlk BT.ttf
  chatbot-ui/src/styles/fonts/futura/Futura-CondensedLight.otf
  chatbot-ui/src/styles/fonts/futura/futur.ttf
  chatbot-ui/src/styles/fonts/futura/futura light bt.ttf
  chatbot-ui/src/styles/fonts/futura/futura medium bt.ttf
  chatbot-ui/src/styles/fonts/futura/futura medium condensed bt.ttf
  chatbot-ui/src/styles/fonts/futura/sharefonts.net.txt
  chatbot-ui/src/styles/fonts/futura/tt0205m_.ttf
  chatbot-ui/src/styles/fonts/futura/unicode.futurab.ttf
  chatbot-ui/src/styles/fonts/futura/unicode.futurabb.ttf
  chatbot-ui/src/styles/fonts/pizzabot.ttf
  chatbot-ui/src/styles/fonts/pizzadudedotdk.txt
  chatbot-ui/src/styles/fonts/read_me.pdf
  chatbot-ui/webpack.config.js
Labels: scratch-code

#12 Update README.md
  README.md
Labels: documentation

#18 WIP (feat): adding server-client link(summarizer)
  __init__.py
  bot-server/__pycache__/handlers.cpython-37.pyc
  bot-server/__pycache__/shorten.cpython-37.pyc
  bot-server/a.txt
  bot-server/classifier.py
  bot-server/controller/__pycache__/handlers.cpython-37.pyc
  bot-server/controller/handlers.py
  bot-server/handlers.py
  bot-server/input.txt
  bot-server/main.py
  bot-server/pkg/summarizer/input_original.txt
  bot-server/pkg/summarizer/summarizer.py
  bot-server/request.txt
  bot-server/shorten.py
  bot-server/summary.txt
  bot-ui/package-lock.json
  bot-ui/package.json
  bot-ui/public/index.html
  bot-ui/src/components/Helper.js
  bot-ui/src/components/InputPortal.js
  bot-ui/src/components/bots/ControlAzul.js
  bot-ui/src/components/bots/ControlIris.js
  bot-ui/src/containers/HomeContainer.js
  bot-ui/src/index.css
  bot-ui/src/styles/components/inputportal.css
  package-lock.json
Labels: backend, frontend, scratch-code

#29 [WIP] Fix frontend routing and UI discrepancies
  Project Expo Proceeding  paper format (1).docx
  assignment-2.pdf
  bot-ui/public/bot.png
  bot-ui/public/index.html
  bot-ui/src/components/EndPage.js
  bot-ui/src/components/InputPortal.js
  bot-ui/src/components/bots/ControlCoral.js
  bot-ui/src/components/bots/ControlIris.js
  bot-ui/src/components/bots/package.json
  bot-ui/src/containers/HomeContainer.js
  bot-ui/src/index.css
  bot-ui/src/styles/components/bots.css
  bot-ui/src/styles/components/endpage.css
  cs-bots-extended-abstract.pdf
  package-lock.json
  software flow.png
Labels: Work-In-Progress, frontend, ui

#30 UI routing
  bot-ui/src/App.js
  bot-ui/src/components/EndPage.js
  bot-ui/src/components/Footer.js
  bot-ui/src/components/Header.js
  bot-ui/src/components/Helper.js
  bot-ui/src/components/InputPortal.js
  bot-ui/src/components/ResultPortal.js
  bot-ui/src/components/SpiderViewPortal.js
  bot-ui/src/components/bots/ControlAzul.js
  bot-ui/src/components/bots/ControlCoral.js
  bot-ui/src/components/bots/ControlIris.js
  bot-ui/src/components/bots/ControlRoux.js
  bot-ui/src/components/history.js
  bot-ui/src/containers/HomeContainer.js
  bot-ui/src/styles/components/endpage.css
  bot-ui/src/styles/components/inputportal.css
  bot-ui/src/styles/components/resultportal.css
  bot-ui/src/styles/containers/home-container.css
Labels: frontend, ui

#31 documentation folder addition
  __init__.py
  documentation/Project Expo Proceeding  paper format (1).docx
  documentation/cs-bots-extended-abstract.pdf
  output_files/software flow.png
Labels: documentation

#33 Updated Readme.md
  README.md
Labels: application-testing, documentation

#34 added bch.yml
  .bettercodehub.yml
  documentation/software flow.png
Labels: code-quality

#37 Added Icon
  bot-ui/public/favicon.ico
Labels: frontend, ui

#35 completed api for classify and summarize
  bot-server/__pycache__/classifier.cpython-37.pyc
  bot-server/__pycache__/handlers.cpython-37.pyc
  bot-server/__pycache__/shorten.cpython-37.pyc
  bot-server/a.txt
  bot-server/api.py
  bot-server/classifier.py
  bot-server/handlers.py
  bot-server/input.txt
  bot-server/main.py
  bot-server/request.txt
  bot-server/shorten.py
  bot-server/summary.txt
  bot-ui/src/components/EndPage.js
  bot-ui/src/components/InputPortal.js
  bot-ui/src/components/ResultPortal.js
  bot-ui/src/components/SpiderViewPortal.js
  bot-ui/src/components/bots/ControlAzul.js
  bot-ui/src/components/bots/ControlIris.js
  bot-ui/src/components/bots/ControlRoux.js
  bot-ui/src/components/bots/package.json
  bot-ui/src/styles/components/inputportal.css
  bot-ui/src/styles/components/resultportal.css
  output-files/classify-output.txt
  output-files/summarize-output.txt
Labels: Work-In-Progress, backend

#42 Readme.md Update
  README.md
  bot-server/__pycache__/classifier.cpython-37.pyc
  bot-server/__pycache__/handlers.cpython-37.pyc
  bot-server/__pycache__/shorten.cpython-37.pyc
  bot-server/handlers.pyc
  bot-server/requirements.txt
  bot-server/shorten.pyc
  output-files/classify-output.txt
  output-files/summarize-output.txt
Labels: documentation

#45 changed title icon
  bot-ui/public/favicon.ico
  documentation/CRM-Implementation-1200x675.png
  documentation/Implementation.png
  documentation/Thesis-Report-format.doc
  documentation/code (1).png
  documentation/code.png
  documentation/d1.png
  documentation/fwddocuments.zip
  documentation/fwddocuments/Copyright.pdf
  documentation/fwddocuments/Fee.pdf
  documentation/fwddocuments/Manuscript_51.docx
  documentation/fwddocuments/Manuscript_51.pdf
  documentation/fwddocuments/Registration.pdf
  documentation/fwddocuments/Studentship.docx
  documentation/fwddocuments/~$nuscript_51.docx
  documentation/https___blogs-images.forbes.com_danielnewman_files_2019_07_Screen-Shot-2019-07-12-at-4.17.00-PM-1200x678.png
  documentation/human-resources-app.png
  documentation/processor.png
  documentation/resource-management-effective-strategies-for-business.jpg
  documentation/testers.png
  documentation/thank-you-hand-drawn-lettering-260nw-780491263.webp
  documentation/~$esis-Report-format.doc
  output-files/classify-output.txt
  output-files/summarize-output.txt
Labels: bug
